### ISSUE TITLE
Demo Applet. The app crashes after tapping the Next/Skip button on the Time Range Widget

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-app#1336]
**Steps to reproduce**:
1. Log in to the app (snakessqa@gmail com // 123456)
2. Tap the demo applet card
3. Take the activity
4. Pay attention to the result

**Actual result:** The app crashes after tapping the Next/Skip button on the Time Range Widget
**Video:** https://www.screencast.com/t/dKWocEwDoF88
**Expected result:** The user should be able to take the activity successfully

**Environment:**
Staging
MindLogger app v 0.14.5
Samsung Galaxy S10 // Android 9
iPhone X // iOS 13.3
Pixel 4 XL // Android 1

**Comment by sergeysemenuta** [comment]
The issue is fixed.
https://www.screencast.com/t/nHxBLlOX
Checked on:
Staging
MindLogger app v 0.14.12
Samsung Galaxy S10 // Android 9
iPhone X // iOS 13.3

**Comment by WorldImpex** [comment]
When entering a time and hitting next it crashes 

MindLogger app v 0.14.5 | iphone 6s 13.

**Comment by WorldImpex** [comment]
Still reproduces 

[https://app.zenhub.com/files/103405139/9b3be358-b3c6-4f32-91ac-663921a39fd7/download](https://app.zenhub.com/files/103405139/9b3be358-b3c6-4f32-91ac-663921a39fd7/download)

**Comment by WorldImpex** [comment]
works as expected on 14.14

**Comment by sergeysemenuta** [comment]
Works as expected on 14.14
iPhone X // iOS 13.3
