### ISSUE TITLE
[UI] Markdown text isn't displayed correctly for all the item types

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-app#1838]
**Preconditions**
The user is logged in on the admin panel and mobile app
https://admin-staging.mindlogger.org/
geria2.test@gmail.com // McgzF127

**Steps to reproduce**
1. Open a site https://admin-staging.mindlogger.org/
2. Open a mobile app
3. On the admin panel proceed to the "DBT Applet 1" applet (password: Qwe123!!!) => About Page
4. Add a markdown text with different item types and save
5. On mobile app proceed to the "DBT Applet 1" applet => About Page
6. Compare the displaying of the page with an expected view on the admin panel

**Actual result**
Markdown text isn't displayed correctly for all the item types.

**Expected result**
Markdown text is displayed correctly for all the item types.

**Notes**
Reproducible for the uploaded from the GitHub applets and manually created applets.

**Screenshots:**
https://www.screencast.com/t/c8OgP5azQ
https://www.screencast.com/t/t4fxKwQdQcHt

**Environment**
ML v0.16.31 (staging)
iPhone XR // iOS 14.3	
Samsung Galaxy S7 Edge SM-G935FD // Android 8.0	
iPhone 8  // iOS 12.3.1	
Samsung A31	// Android 10
https://admin-staging.mindlogger.org/
Windows 10 x64 // Chrome 91.0.4472.106
MacBook Air (13-inch, 2020) // Big Sur 11.0 // Safari

**Comment by natalia-muzyka** [comment]
iOS & Android: 
1) Images from DBT Daily Diary Card schema are still displayed as a code:
https://www.screencast.com/t/uRqR3a0nR
2) CA Partners applet still shows 404 Not found
https://www.screencast.com/t/Cx4rYZ8xU
3) Video uploaded via link isn't displayed at all(on the admin panel there is also an error after adding a link, commented about this [here](https://app.zenhub.com/workspaces/mindlogger-webapp-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-applet-builder/361))

iOS:
The uploaded audio file can't be replayed (infinity loader on the player)
https://www.screencast.com/t/YlFtUKXciiiz

Android:
Crash on markdown with audio link ([reported](https://app.zenhub.com/workspaces/mindlogger-webapp-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-app/1825))

**Environment**:
ML v0.16.35 (staging)
iPhone XR // iOS 14.3
Samsung Galaxy S7 Edge SM-G935FD // Android 8.0
Samsung A31 // Android 10
Applets: 
All(1), DBT Daily Diary Card, CA Partners, DBT Applet 1
Applets password: Qwe123!!!)

**Comment by WorldImpex** [comment]
Based on what @devbtech has provided. 2 and 6 are completed per the below screenshot. The other ideas will be worked on in future milestones and this ticket can go to the top of the backlog once confirmed fixed by @natalia-muzyka 

![image.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/3b71b791-59d6-47e5-bf5e-fb518c861343)

**Comment by devbtech** [comment]
Here's latest update. 2), 3) and 6) are fixed as per screenshot below.

![image.png](https://images.zenhubusercontent.com/5e248ca6aaf6ad9f4a061291/f8d4eba4-74f7-4218-b14b-0f54c4e6504c)

**Comment by natalia-muzyka** [comment]
**verified as fixed:**
#2, 3, 
iOS audio file isn't replayed,  
Android crash on markdown with audio link
https://www.screencast.com/t/npJrNdRNqlC

ML v0.17.8 (staging)
Samsung Galaxy S7 Edge SM-G935FD // Android 8.0
iPhone 6 Plus  // iOS 12.4.8

**Comment by devbtech** [comment]
All issues above are fixed except superscript

**Comment by natalia-muzyka** [comment]
@devbtech 
verified as fixed on the About page,
but on the activity screen(markdown item and the text/large text value) the mark and subscript are still not displayed:
https://www.screencast.com/t/rfqFFYU24hL

ML v0.17.14 (staging)
Samsung Galaxy S7 Edge SM-G935FD // Android 8.0	
iPhone 7 // iOS 13.1.1

**Comment by natalia-muzyka** [comment]
verified: all the issues are fixed except the superscript
https://www.screencast.com/t/kQ0aK3YPcqW

ML v 0.17.15 (staging)
Samsung Galaxy S7 Edge SM-G935FD // Android 8.0
iPhone 7 // iOS 13.1.1
