### ISSUE TITLE
slider widget is not schema compliant

### ISSUE THREAD

**Issue by akeshavan** [ChildMindInstitute/mindlogger-app#289]
see https://github.com/ChildMindInstitute/mindlogger-app/blob/master/app/widgets/Slider/index.js#L21-L22

instead of setting the min value to 0 and max to the length of the items in the list, we need to extract the min and max values from the items in the list and plug it in there.

**Comment by akeshavan** [comment]
@shnizzedy this is why the plots on that one HBN question are going off the page. The schema says the min and max value are 0 and 5, but the slider widget encodes it as 1 - 6

**Comment by InheritxSolution** [comment]
I was checking this issue and you can see the schema which I received was below :

> { description: { en: 'How much your child enjoyed the day' },
         schemaVersion: { en: '0.0.1' },
         version: { en: '0.0.1' },
         altLabel: { en: 'enjoyed_day' },
         inputType: 'slider',
         question: { en: 'Did your child seem like they enjoyed the day?' },
         preamble: undefined,
         timer: undefined,
         delay: undefined,
         valueConstraints: 
          { itemList: 
             [ { name: { en: '1' },
                 value: 1,
                 image: 'https://childmindinstitute.github.io/mindlogger-assets/emojis/openmoji/1F621.svg',
                 valueConstraints: undefined },
               { name: { en: '2' },
                 value: 2,
                 image: undefined,
                 valueConstraints: undefined },
               { name: { en: '3' },
                 value: 3,
                 image: undefined,
                 valueConstraints: undefined },
               { name: { en: '4' },
                 value: 4,
                 image: undefined,
                 valueConstraints: undefined },
               { name: { en: '5' },
                 value: 5,
                 image: 'https://childmindinstitute.github.io/mindlogger-assets/emojis/openmoji/1F601.svg',
                 valueConstraints: undefined } ],
            **maxValue: 'Really enjoying things',
            minValue: 'No enjoyment or pleasure'** }`

I have marked maximum and minimum value in bold so instead of maximum and minimum value in integer manner, it is coming in the string but I have made it dynamic value for maxValue so, for now, it is working as expected.

**Comment by WorldImpex** [comment]
@shnizzedy Could you confirm this is fixed?

**Comment by shnizzedy** [comment]
> Could you confirm this is fixed?

I think this is not fixed. I loaded https://raw.githubusercontent.com/ReproNim/reproschema/master/protocols/mindlogger-demo/mindlogger-demo_schema which includes a 0‒5 slider:

https://github.com/ReproNim/reproschema/blob/fcc4fbdf25311717572ac9714bf1c9bd50e537c9/activities/MindLoggerDemo/items/slider#L21-L47

When I tried it, though, the range showed as 1‒6, and when I chose the lowest option, it saved as `1`, not `0`.

![not fixed screengrab](https://user-images.githubusercontent.com/5974438/72295890-70f54200-3626-11ea-8835-4d590aaba68c.gif)

```json
{
  "responses": {
    "reprolib:activities/MindLoggerDemo/items/radio": [
      {
        "date": "2020-01-13",
        "value": 1
      }
    ],
    "reprolib:activities/MindLoggerDemo/items/slider": [
      {
        "date": "2020-01-13",
        "value": 1
      }
    ]
  },
  "schema:duration": "P7D",
  "schema:endDate": "2020-01-13",
  "schema:startDate": "2020-01-06"
}
```

![data tab](https://user-images.githubusercontent.com/5974438/72295420-84ec7400-3625-11ea-97b8-829c7a3b7ba5.png)

**Comment by WorldImpex** [comment]
Selected lowest option on slider which should be a 0. Checked data and it shows as a 0 on the graph. fixed. 

![File (3).jpg](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/52e6b0af-a74d-43dd-b396-6197b1b53497)
