### ISSUE TITLE
Text within Assessment showing incorrectly

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#621]
Expected Results: Text throughout the assessment show as correct English grammar 
Actual Results: Text shows as ? with diamond behind

Environment: iPhone 6s 13.3/ v0.9.11

![IMG_0042.PNG](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/2e0cb049-7481-4566-b2d4-3fed9d671a5b)

**Comment by hotavocado** [comment]
This should be fixed now, had some strange characters in my applet csv.

**Comment by WorldImpex** [comment]
@hotavocado This is still reproducible on the newest version 0.9.12

**Comment by WorldImpex** [comment]
confirmed fixed 

![File](https://user-images.githubusercontent.com/22243307/72358066-f970f280-36b9-11ea-88ad-a73e6691cb62.jpg)
