### ISSUE TITLE
Remove / between "Very sad" 

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#632]
Expected Result: The user views very sad in correct english grammar 
Actual Result: Phrase displayed as very / sad 

Environment: iPhone 6s 13.3/ v0.9.11

![68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3565313333366631623234303235613762323635343437352f63656263623464652d366238312d343434332d623664322d626363326635363564393831.jpeg](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/ee7cb19a-bddc-47c5-9bc9-00405d4f794f)

**Comment by hotavocado** [comment]
resolved via https://github.com/hotavocado/HBN_EMA_NIMH2/commit/27c307f254e22dc15118ab81d195cf2111f04caa

**Comment by WorldImpex** [comment]
resolved via hotavocado/HBN_EMA_NIMH2@27c307f

**Comment by WorldImpex** [comment]
@hotavocado This is still reproducible in newest version 0.9.12

**Comment by hotavocado** [comment]
![Screenshot_20200113_114018_lab childmindinstitute data](https://user-images.githubusercontent.com/24463939/72274396-1b0aa500-35fa-11ea-84e2-85b02ff1a104.jpg)

Worked for me after I refreshed my applets on https://api.mindlogger.org/

**Comment by WorldImpex** [comment]
confirmed fixed 

![File (1)](https://user-images.githubusercontent.com/22243307/72358183-258c7380-36ba-11ea-870c-65a1df3aab85.jpg)
